@echo off
cd /d "%~dp0"
powershell -NoProfile -ExecutionPolicy Bypass -Command "Get-Content '%~f0' | Select-Object -Skip 4 | Out-String | Invoke-Expression"
goto :EOF

# ============================================================
# Build the SDG Pathways Explorer release ZIPs (Windows Native)
# ============================================================
$ErrorActionPreference = "Stop"

# Load the reliable native Windows .NET compression engine
Add-Type -AssemblyName System.IO.Compression.FileSystem

# Move up to the project root directory (assuming script is in tools/)
Set-Location ..
# Force the underlying .NET engine to sync its directory with PowerShell
[System.Environment]::CurrentDirectory = $PWD.ProviderPath

$LEVELS = @("primary", "secondary", "pre-university")
$DIST = "dist"

# ------------------------------------------------------------
# 1. Regenerate the committed preview content.js (all three levels).
# ------------------------------------------------------------
$contentPath = "data/content.js"
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("// AUTO-GENERATED by tools/build-zips.bat - do not edit by hand.")
[void]$sb.AppendLine("// Combined preview pack: registers all three levels so index.html shows")
[void]$sb.AppendLine("// the level picker and the on-page level switch. A shipped single-level")
[void]$sb.AppendLine("// build replaces this file with one data/content-<level>.js instead.")
[void]$sb.AppendLine("// Edit the per-level source files, then re-run tools/build-zips.bat.")
[void]$sb.AppendLine()

foreach ($lvl in $LEVELS) {
    [void]$sb.AppendLine("// ===== data/content-$lvl.js =====")
    if (Test-Path "data/content-$lvl.js") {
        [void]$sb.AppendLine((Get-Content "data/content-$lvl.js" -Raw))
    } else {
        Write-Error "Missing source file: data/content-$lvl.js"
    }
    [void]$sb.AppendLine()
}

if (-not (Test-Path "data")) { New-Item -ItemType Directory -Path "data" | Out-Null }
Set-Content -Path $contentPath -Value $sb.ToString() -Encoding utf8
Write-Host "regenerated data/content.js (preview = all levels)"

# ------------------------------------------------------------
# 1b. Stamp the asset cache-busting version into index.html.
# ------------------------------------------------------------
$combinedText = (Get-Content "data/sdg-content.js" -Raw) + (Get-Content "data/content.js" -Raw)
$tmpHashFile = [System.IO.Path]::GetTempFileName()
Set-Content -Path $tmpHashFile -Value $combinedText -Encoding utf8
$VER = (Get-FileHash $tmpHashFile -Algorithm MD5).Hash
Remove-Item $tmpHashFile

if (Test-Path "index.html") {
    $indexContent = Get-Content "index.html" -Raw
    $regex = '(data/(sdg-content|content)\.js)\?v=[A-Za-z0-9]+'
    $newIndexContent = $indexContent -replace $regex, "`$1?v=$VER"
    Set-Content "index.html" -Value $newIndexContent -Encoding utf8
    Write-Host "stamped index.html asset version v=$VER"
} else {
    Write-Error "index.html not found!"
}

# ------------------------------------------------------------
# 2. Assemble the ZIPs.
# ------------------------------------------------------------
if (Test-Path $DIST) { Remove-Item -Recurse -Force $DIST }
New-Item -ItemType Directory -Path $DIST -Force | Out-Null

function Stage-Common ($stagePath) {
    New-Item -ItemType Directory -Path "$stagePath\data" -Force | Out-Null
    Copy-Item "index.html" -Destination "$stagePath\"
    Copy-Item "data/sdg-content.js" -Destination "$stagePath\data\"
    if (Test-Path "fonts") { Copy-Item "fonts" -Destination "$stagePath\" -Recurse }
    if (Test-Path "icons") { Copy-Item "icons" -Destination "$stagePath\" -Recurse }
}

function Make-Zip ($name, $contentSrc) {
    $stage = "$DIST\stage-$name"
    if (Test-Path $stage) { Remove-Item -Recurse -Force $stage }
    New-Item -ItemType Directory -Path $stage -Force | Out-Null
    
    Stage-Common $stage
    Copy-Item $contentSrc -Destination "$stage\data\content.js"
    
    # Explicitly build absolute paths using PowerShell's true current directory
    $absoluteStage = Join-Path $PWD.ProviderPath $stage
    $absoluteZip = Join-Path $PWD.ProviderPath "$DIST\sdg-explorer-$name.zip"
    
    if (Test-Path $absoluteZip) { Remove-Item $absoluteZip }
    
    # Create the ZIP cleanly using the absolute paths
    [System.IO.Compression.ZipFile]::CreateFromDirectory($absoluteStage, $absoluteZip)
    
    Remove-Item -Recurse -Force $stage
    Write-Host "built $DIST/sdg-explorer-$name.zip"
}

# One ZIP per single level
foreach ($lvl in $LEVELS) {
    Make-Zip $lvl "data/content-$lvl.js"
}

# Combined preview ZIP
Make-Zip "preview" "data/content.js"

Write-Host "`ndone. ZIPs are in $DIST/"
Read-Host "Press Enter to exit..."
