#!/usr/bin/env bash
# ============================================================
# Build the SDG Pathways Explorer release ZIPs.
# ============================================================
# Architecture
#   index.html + data/sdg-content.js are the shared BASE, identical in every
#   build. The active age level is whatever data/content.js registers:
#     - one  data/content-<level>.js  -> single-level build (boots that level,
#                                         no level picker)
#     - all three concatenated        -> combined "preview" build (picker +
#                                         on-page level switch)
#
# Editors only ever edit the three source files:
#   data/content-primary.js
#   data/content-secondary.js
#   data/content-pre-university.js
# Run this script afterwards to regenerate the committed preview data/content.js
# and the four release ZIPs in dist/.
#
# Usage:  bash tools/build-zips.sh
# Requires: bash, zip.
# ============================================================
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

LEVELS=(primary secondary pre-university)
DIST="dist"

# ------------------------------------------------------------
# 1. Regenerate the committed preview content.js (all three levels).
# ------------------------------------------------------------
{
  echo "// AUTO-GENERATED by tools/build-zips.sh - do not edit by hand."
  echo "// Combined preview pack: registers all three levels so index.html shows"
  echo "// the level picker and the on-page level switch. A shipped single-level"
  echo "// build replaces this file with one data/content-<level>.js instead."
  echo "// Edit the per-level source files, then re-run tools/build-zips.sh."
  echo
  for lvl in "${LEVELS[@]}"; do
    echo "// ===== data/content-$lvl.js ====="
    cat "data/content-$lvl.js"
    echo
  done
} > data/content.js
echo "regenerated data/content.js (preview = all levels)"

# ------------------------------------------------------------
# 2. Assemble the ZIPs.
# ------------------------------------------------------------
rm -rf "$DIST"
mkdir -p "$DIST"

stage_common() {            # $1 = staging dir; copies the unchanging base.
  mkdir -p "$1/data"
  cp index.html "$1/"
  cp data/sdg-content.js "$1/data/"
  cp -r fonts "$1/"
  cp -r icons "$1/"
}

make_zip() {                # $1 = build name; $2 = path to the content.js to use.
  local name="$1" content="$2"
  local stage="$DIST/stage-$name"
  rm -rf "$stage"; mkdir -p "$stage"
  stage_common "$stage"
  cp "$content" "$stage/data/content.js"
  ( cd "$stage" && zip -qr "../sdg-explorer-$name.zip" . )
  rm -rf "$stage"
  echo "built $DIST/sdg-explorer-$name.zip"
}

# One ZIP per single level (auto-boots that level, no picker).
for lvl in "${LEVELS[@]}"; do
  make_zip "$lvl" "data/content-$lvl.js"
done

# Combined preview ZIP (picker + level switch).
make_zip "preview" "data/content.js"

echo "done. ZIPs are in $DIST/"
